<script setup lang="ts">
import BrainStatePanel from '@/components/brain/BrainStatePanel.vue'
import BrainScene from '@/components/scene/BrainScene.vue'
import { useBrainStream } from '@/composables/useBrainStream'

useBrainStream()
</script>

<template>
  <main class="dashboard">
    <header class="dashboard__header">
      <a class="brand" href="/" aria-label="Brain AI Visualizer home">
        <span class="brand__mark" aria-hidden="true">
          <i />
          <i />
          <i />
        </span>
        <span>
          <strong>Brain AI</strong>
          <small>Visualizer</small>
        </span>
      </a>

      <div class="environment">
        <span>Mock environment</span>
        <span>Milestone 07</span>
      </div>
    </header>

    <section class="dashboard__visual">
      <div class="dashboard__intro">
        <p class="dashboard__eyebrow">Neural intelligence interface</p>
        <h1>See the state<br />behind the signal.</h1>
        <p class="dashboard__description">
          A real-time view of EEG activity, cognitive state, emotion, and core
          attention metrics generated by the mock prediction stream.
        </p>
      </div>

      <BrainScene />
    </section>

    <aside class="dashboard__panel">
      <BrainStatePanel />
    </aside>

    <footer class="dashboard__footer">
      <span>10 EEG channels</span>
      <span>1 Hz mock prediction stream</span>
      <span>Facial morph smoothing</span>
    </footer>
  </main>
</template>

<style scoped>
.dashboard {
  position: relative;
  display: grid;
  grid-template-columns: minmax(18rem, 0.85fr) minmax(28rem, 1.15fr);
  grid-template-rows: auto 1fr auto;
  gap: 2rem 5rem;
  min-height: 100vh;
  max-width: 86rem;
  margin: 0 auto;
  padding: 2rem 3rem;
}

.dashboard::before {
  position: fixed;
  z-index: -1;
  top: 12%;
  left: 8%;
  width: 28rem;
  height: 28rem;
  border: 1px solid rgba(81, 230, 196, 0.07);
  border-radius: 50%;
  box-shadow:
    0 0 0 4rem rgba(81, 230, 196, 0.015),
    0 0 0 9rem rgba(81, 230, 196, 0.01);
  content: '';
}

.dashboard__header {
  grid-column: 1 / -1;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.brand {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  color: #f8fafc;
  text-decoration: none;
}

.brand__mark {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.16rem;
  width: 2.15rem;
  height: 2.15rem;
  border: 1px solid rgba(81, 230, 196, 0.26);
  border-radius: 50%;
  background: rgba(81, 230, 196, 0.06);
}

.brand__mark i {
  width: 0.13rem;
  height: 0.7rem;
  border-radius: 99px;
  background: #51e6c4;
}

.brand__mark i:nth-child(2) { height: 1rem; }
.brand__mark i:nth-child(3) { height: 0.45rem; }

.brand strong,
.brand small {
  display: block;
}

.brand strong {
  font-size: 0.84rem;
  letter-spacing: -0.01em;
}

.brand small {
  margin-top: 0.1rem;
  color: #64748b;
  font-size: 0.62rem;
  letter-spacing: 0.11em;
  text-transform: uppercase;
}

.environment {
  display: flex;
  gap: 0.65rem;
}

.environment span {
  padding: 0.45rem 0.7rem;
  border: 1px solid rgba(148, 163, 184, 0.13);
  border-radius: 999px;
  color: #64748b;
  font-size: 0.62rem;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

.dashboard__visual {
  align-self: center;
  display: grid;
  gap: 1.75rem;
  width: 100%;
  max-width: 32rem;
}

.dashboard__intro {
  max-width: 30rem;
}

.dashboard__eyebrow {
  margin: 0 0 1.2rem;
  color: #51e6c4;
  font-size: 0.68rem;
  font-weight: 700;
  letter-spacing: 0.16em;
  text-transform: uppercase;
}

.dashboard h1 {
  margin: 0;
  color: #f8fafc;
  font-size: clamp(3rem, 5.5vw, 5.4rem);
  font-weight: 520;
  line-height: 0.92;
  letter-spacing: -0.065em;
}

.dashboard__description {
  max-width: 27rem;
  margin: 2rem 0 0;
  color: #7c8ca1;
  font-size: 0.88rem;
  line-height: 1.8;
}

.dashboard__panel {
  align-self: center;
  width: 100%;
  max-width: 43rem;
  justify-self: end;
}

.dashboard__footer {
  grid-column: 1 / -1;
  display: flex;
  gap: 1.5rem;
  padding-top: 1.2rem;
  color: #475569;
  border-top: 1px solid rgba(148, 163, 184, 0.1);
  font-size: 0.64rem;
}

.dashboard__footer span:not(:last-child)::after {
  margin-left: 1.5rem;
  color: #1e293b;
  content: '•';
}

@media (max-width: 960px) {
  .dashboard {
    grid-template-columns: 1fr;
    padding: 1.5rem;
  }

  .dashboard__visual {
    max-width: none;
    padding: 3rem 0 1rem;
  }

  .dashboard__panel {
    max-width: none;
  }
}

@media (max-width: 560px) {
  .dashboard {
    padding: 1rem;
  }

  .environment span:first-child,
  .dashboard__footer span:not(:first-child) {
    display: none;
  }

  .dashboard__visual {
    padding-top: 2rem;
  }
}
</style>
